In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([9,16,25,32,49,54])
y = x/2+x**(1/2)
X = np.array([22,36])
Y = X/2+X**(1/2)
print(y)
print(Y)
# temp=0
# print(np.arange(10))
# for j in np.arange(0,100):
#     if(temp>60):
#         print(j)
#         break
#     else:
#         for i in np.arange(0,10):
#             temp=temp+i
#         print(i)
# print(temp)

[ 7.5        12.         17.5        21.65685425 31.5        34.34846923]
[15.69041576 24.        ]


In [3]:
class CPN(object):
    #初始化
    def __init__(self,delta=7,alpha=0.5,beta=0.5):
        self.delta = delta
        self.alpha = alpha
        self.beta = beta
        self.w = []
        self.pi = []
        self.delta_w = []
        self.delta_pi = []
        self.temp = 0
        
        
    #隱藏層    
    def update(self,x,y):
        #暫存值用來儲存前一次規則數
        self.temp = len(self.w)
        print(self.w)
        for i in np.arange(0,6):
            #建立第一個規則單元
            if(i==0):
                self.w.append(x[i])
                self.pi.append(y[i])
            else:
                #權重與輸入x值得最短距離
                distance_1 = np.min(abs(self.w-x[i]))
                distance_2 = np.min(abs(self.pi-y[i]))
                #找出最短距離得權重值的位置
                index = np.where(abs(self.w-x[i])==distance_1)[0][0]
                if((distance_1<=self.delta)):
                    #更新權重值，贏者全拿機制
                    self.delta_w.append(self.alpha*(x[i]-self.w[index]))
                    self.delta_pi.append(self.beta*(y[i]-self.pi[index]))
                    self.w[index] = self.w[index]+self.alpha*(x[i]-self.w[index])
                    self.pi[index] = self.pi[index]+self.beta*(y[i]-self.pi[index])
                else:
                    #否則，建立新的規則單元
                    self.w.append(x[i])
                    self.pi.append(y[i])
    
    def train(self,x,y):
        self.temp = len(self.w)
        print(self.w)
        for i in np.arange(0,6):
            #權重與輸入x值得最短距離
            distance_1 = np.min(abs(self.w-x[i]))
            distance_2 = np.min(abs(self.pi-y[i]))
            #找出最短距離之權重值得位置
            index = np.where(abs(self.w-x[i])==distance_1)[0][0]
            if((distance_1<=self.delta)):
                #更新權重值，贏者全拿機制
                self.delta_w.append(self.alpha*(x[i]-self.w[index]))
                self.delta_pi.append(self.beta*(y[i]-self.pi[index]))
                self.w[index] = self.w[index]+self.alpha*(x[i]-self.w[index])
                self.pi[index] = self.pi[index]+self.beta*(y[i]-self.pi[index])
            else:
                #否則，建立新的規則單元
                self.w.append(x[i])
                self.pi.append(y[i])
                
    #輸出層
    def fuzzy(self,x):
        for i in np.arange(0,2):
            #權重和輸入的距離
            d = ((self.w-x[i])**2)**(1/2)
            #D表示輸入x和規則單元的相對距離
            D = np.zeros((1,len(self.w)))
            #S表示相似度
            S = np.zeros((1,len(self.w)))
            for j in np.arange(0,len(self.w)):
                if(d[j]<=20):
                    D[0,j] = d[j]/20.0
                else:
                    D[0,j] = 1
                S[0,j] = 1-D[0,j]
            #輸出y值，使用fuzzy重心法
            output = np.sum(S*self.pi)/np.sum(S)
            print(d)
            print(S)
            print(output)

In [4]:
cpn = CPN()
cpn.update(x,y)
print(cpn.w)
#停止迭代條件
for i in np.arange(0,10):
    if(len(cpn.w)==cpn.temp):
        print(i)
        break
    else:
        cpn.train(x,y)
        print(cpn.w)
cpn.fuzzy(X)
print(cpn.delta_w)
print(cpn.delta_pi)

[]
[12.5, 28.5, 51.5]
[12.5, 28.5, 51.5]
[13.375, 29.375, 52.125]
1
[ 8.625  7.375 30.125]
[[0.56875 0.63125 0.     ]]
15.460098565100035
[22.625  6.625 16.125]
[[0.      0.66875 0.19375]]
23.059266081406346
[3.5, 3.5, 2.5, -1.75, 2.625, -1.75, 2.625, -1.25, 1.875]
[2.25, 2.07842712474619, 1.4242346141747682, -1.125, 1.6875, -1.0392135623730958, 1.558820343559642, -0.7121173070873823, 1.068175960631077]
