In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3],
           [2,3,4]])

print(array)
print(array.shape)
print(array.size)

[[1 2 3]
 [2 3 4]]
(2, 3)
6


In [4]:
a = np.array([2,23,4],dtype=np.float64)
print(a.dtype)

float64


In [7]:
b = np.zeros((1,4))
print(b)
print(b[0,1])

[[0. 0. 0. 0.]]
0.0


In [6]:
c = np.ones((3,4),dtype=np.int16)
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
d = np.empty((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
e = np.arange(10,20,2)
print(e)

[10 12 14 16 18]


In [30]:
f = np.arange(12).reshape((3,4))
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
g = np.linspace(1,10,6).reshape((2,3))
print(g)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [36]:
h = np.array([10,20,30,40])
i = np.arange(4)
j = h-i
k = i**2
l = 10*np.sin(h)
print(j)
print(k)
print(l)

[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [42]:
m =  np.array([[1,1],
             [0,1]])
n = np.arange(4).reshape((2,2))
print(m)
print(n)
o = m*n
o_dot = np.dot(m,n)
o_dot_2 = m.dot(n)
print(o)
print(o_dot)
print(o_dot_2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [46]:
p = np.random.random((2,4))
print(p)
print(np.sum(p))
print(np.min(p))
print(np.max(p))
print(np.sum(p,axis=1))
print(np.min(p,axis=0))
print(np.max(p,axis=1))

[[0.04969727 0.56373745 0.36352582 0.22656967]
 [0.73911398 0.08500196 0.39193907 0.26675609]]
2.6863413188356042
0.0496972713349243
0.7391139813701899
[1.20353021 1.48281111]
[0.04969727 0.08500196 0.36352582 0.22656967]
[0.56373745 0.73911398]


In [25]:
A = np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A))
print(np.argmax(A))
print(np.mean(A))
print(A.mean())
print(np.average(A))
print(np.median(A))
print(np.cumsum(A))
print(np.diff(A))
print(np.sort(A))
print(np.transpose(A))
print(A.T)
print((A.T).dot(A))
print(np.clip(A,5,9))
print(np.mean(A,axis=1))
print(np.mean(A,axis=0))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
[ 3.5  7.5 11.5]
[6. 7. 8. 9.]


In [17]:
B = np.arange(3,15).reshape((3,4))
print(B)
print(B[2])
print(B[2][1])
print(B[2,1])
print(B[2,:])
print(B[:,2])
print(B[1,1:3])
for row in B:
    print(row)
for column in B.T:
    print(column)
print(B.flatten())
for item in B.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
12
12
[11 12 13 14]
[ 5  9 13]
[8 9]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [22]:
C = np.array([1,1,1])
D = np.array([2,2,2])
E = np.vstack((C,D)) #vertical stack
F = np.hstack((C,D)) #horizontal stack
print(E.shape)
print(F)
print(C.T)

(2, 3)
[1 1 1 2 2 2]
[1 1 1]


In [28]:
G = C[:,np.newaxis]
H = D[:,np.newaxis]
print(G)
I = np.vstack((G,H))
J = np.hstack((G,H))
print(I.shape)
print(J.shape)

[[1]
 [1]
 [1]]
(6, 1)
(3, 2)


In [29]:
L = np.concatenate((G,H),axis=0)
M = np.concatenate((G,H),axis=1)
print(L)
print(M)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]


In [34]:
N = np.arange(12).reshape((3,4))
print(N)
print(np.split(N,2,axis=1))
print(np.split(N,3,axis=0))
print(np.array_split(N,3,axis=1))
print(np.vsplit(N,3))
print(np.hsplit(N,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
